services:
  app:
    image: ghcr.io/woolball-xyz/client-node:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_WEBSOCKET_URL: ws://localhost:9003/ws
        VITE_API_URL: http://localhost:9002/api/v1
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NODE_ENV=production 